SELECT ROUND(COALESCE(SUM(TIV_2016),null),2) AS TIV_2016
FROM insurance
WHERE TIV_2015 IN (SELECT TIV_2015 FROM insurance GROUP BY TIV_2015 HAVING COUNT(TIV_2015) > 1)
AND (LAT,LON) IN (SELECT LAT,LON FROM insurance GROUP BY LAT,LON HAVING COUNT(*) = 1)

--2.
SELECT SUM(TIV_2016) AS TIV_2016
FROM(
SELECT *, 
       COUNT(*)OVER(PARTITION BY TIV_2015) AS CNT1, 
       COUNT(*)OVER(PARTITION BY LAT, LON) AS CNT2
FROM insurance) tmp
WHERE CNT1 >1 AND CNT2 = 1
